# start with: docker compose up

services:
  fbk-glasses-bot:
    container_name: fbk-glasses-bot
    restart: always
    
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: local/fbk-glasses-bot
    pull_policy: never
    
    command: "/launch.sh"
    volumes:
      - ${PWD}/config.json:/opt/fbk_glasses_bot/config.json

    logging:
      driver:  json-file
      options:
        max-file: "3"
        max-size: "10M"
